### ISSUE TITLE
ssl key support ??

### ISSUE THREAD

**Issue by binups** [JonZeolla/jzeolla-metron-bro-plugin-kafka#3]
this is  metron-bro-plugin-kafka is support with ssl key support ?  i not finding  any example  for  bro-plugin-kafka   with ssl key

**Comment by JonZeolla** [comment]
Hi @binups, please note that this repo should not be used in any way (including for discussion like this) as it is a personal remnant from when I broke out this plugin to it's own repo and turned it into a package.  Please look at apache/metron-bro-plugin-kafka and the Metron mailing lists (https://lists.apache.org/list.html?dev@metron.apache.org).  Thanks and I look forward to our discussion in one of those areas.
